### ISSUE TITLE
Future Enhancements: Domain names as handles

### ISSUE THREAD

**Issue by tesaguri** [swicg/activitypub-webfinger#17]
Quoting from the SWICG mailing list:

Re: "ActivityPub and Webfinger" CG Note, First Draft from Manton Reece on 2024-03-25 (public-swicg@w3.org from March 2024)
https://lists.w3.org/Archives/Public/public-swicg/2024Mar/0047.html

> Another idea for the "Future Enhancements" section… There has been discussion in the past about better support for single-user servers. For example, instead of the redundant @user@user.com, clients should be able to reference a user with just @user.com. This would also encourage people to own their identity with their own domain name.
>
> Would it be appropriate to formalize this in the report? It could go through the FEP process too, but this report is going to be something that everyone reads about WebFinger.

Re: "ActivityPub and Webfinger" CG Note, First Draft from a on 2024-03-25 (public-swicg@w3.org from March 2024)
https://lists.w3.org/Archives/Public/public-swicg/2024Mar/0048.html

> > Would it be appropriate to formalize this in the report?
>
> I think it makes sense to mention it as an idea, but not specify an exact mechanism at this time.

**Comment by trwnh** [comment]
https://lists.w3.org/Archives/Public/public-swicg/2024Mar/0055.html

> I think this mechanism is somewhat redundant because if
the actor id is already known as `https://user.com/` (from the perspective
of the service/client) discovery should not really be needed.

https://lists.w3.org/Archives/Public/public-swicg/2024Mar/0052.html

> I agree it does seem straightforward to just pass the URL for the domain
> name to WebFinger. I don't think that is redundant, because an actor ID
> might still be a unique, longer URL than just the domain name.
> 
> In other words, you might have:
> 
> Fediverse handle: `@user.com`
> WebFinger: `resource=https://user.com/`
> Actor: `https://user.com/activitypub`
> 
> This is convenient because it moves the content-negotiation pieces away
> from the user's home page, which might be a blog or something not
> entirely ActivityPub-powered.
> 
> That still leaves what to do about "preferredUsername". Should it be
> blank? Should it be "_" as Nostr uses? Should it be the domain name
> itself, similar to how Bridgy Fed uses `@user.com@user.com` fediverse
> handles?

**Comment by pfefferle** [comment]
I agree with @trwnh this is something that has to be handled in the UI because WebFinger already supports everything that is needed.

FYI: https://github.com/mastodon/mastodon/issues/22213

And my comment to that: https://github.com/mastodon/mastodon/issues/22213#issuecomment-1847277898

For WordPress we also implemented the `_` and `*`, but I would prefer using the host (http(s)) instead: https://github.com/Automattic/wordpress-activitypub/pull/594

**Comment by tesaguri** [comment]
Related discussion in the Fediverse Ideas issue tracker:

#23 - Domain names as handles - fediverse/fediverse-ideas - Codeberg.org
https://codeberg.org/fediverse/fediverse-ideas/issues/23
