### ISSUE TITLE
3.1 Limitiations on usernames and hostnames - syntatic specification of the userpart

### ISSUE THREAD

**Issue by AaronNGray** [swicg/activitypub-webfinger#23]
I cannot find any reference, description, or meaning of the usage of the **0\*** multiplicity operator in the document or in [RFC7565](https://www.rfc-editor.org/rfc/rfc7565.html) or [RFC 5234](https://www.rfc-editor.org/rfc/rfc5234.html).
```
userpart     = unreserved / sub-delims
               0*( unreserved / pct-encoded / sub-delims )
```

**Comment by trwnh** [comment]
The ABNF was taken directly from RFC 7565 Section 7 "IANA Considerations" > "URI Scheme Syntax"

The `a*b` syntax is "variable repetition" as defined in RFC 5234 Section 3.6: https://www.rfc-editor.org/rfc/rfc5234.html#section-3.6

It means "at least 0". Granted, this is already the default value for a, so I assume the authors of RFC 7565 wanted to be even more explicit for some reason.

**Comment by AaronNGray** [comment]
Can we specify this in the document as its not immediately obvious.

Also can we add a Regular expression defintion for usernames too please ?

**Comment by evanp** [comment]
Why does this issue require synchronous discussion by the whole CG?
