### ISSUE TITLE
Describe link format in JRD

### ISSUE THREAD

**Issue by evanp** [swicg/activitypub-webfinger#3]
Describe how the `links` item is formatted:

- rel=self
- type=application/activity+json

**Comment by silverpill** [comment]
>type=application/activity+json

Shouldn't ActivityPub media type be used to describe link target?

`application/ld+json; profile="https://www.w3.org/ns/activitystreams"`

Existing implementations usually support both variants.

**Comment by pfefferle** [comment]
@silverpill I am not sure that `profile` is supported by JRD and `application/activity+json` is already the de-facto standard, so we could break a lot of implementations if changing it.

**Comment by pfefferle** [comment]
Hmmm, it seems that Mastodon supports both: https://docs.joinmastodon.org/spec/webfinger/#mastodons-requirements-for-webfinger 🤔

**Comment by trwnh** [comment]
@pfefferle Both are standard. activity+json is preferred by AS2 and ld+json with a profile is mandated by AP for GET/POST.

**Comment by pfefferle** [comment]
Yes, as Content-Type and Accept Header, but I am still irritated by using a profile in XRDs/JRDs `type`. But maybe it is simply because I haven't seen it anywhere yet.

**Comment by tesaguri** [comment]
I think it's worth noting that Lemmy (probably among others) uses the `properties` object with a `
https://www.w3.org/ns/activitystreams#type` "property" to distinguish between `Person` and `Group` actors with a same username (cf. <https://github.com/mastodon/mastodon/pull/19059#issuecomment-1875154293>), although there's no such property as `as:type` in Activity Streams (the `type` term of Activity Streams is an alias of the `@type` keyword of JSON-LD, which in turn implies the `type` property defined under the `rdf:` namespace rather than the `as:` namespace).

**Comment by pfefferle** [comment]
This looks like an adaption of this FEP for NodeInfo: https://codeberg.org/fediverse/fep/src/branch/main/fep/2677/fep-2677.md

We also adopted it for the WordPress plugin: https://notiz.blog/.well-known/webfinger?resource=acct:notiz.blog@notiz.blog

**Comment by silverpill** [comment]
>@silverpill I am not sure that profile is supported by JRD and application/activity+json is already the de-facto standard, so we could break a lot of implementations if changing it.

@pfefferle I'm using ld+json variant in JRD and haven't had any interop issues so far. I think many implementations don't check `type` property at all and just take the first `self` link. Others, like Mastodon, support both media types.

**Comment by pfefferle** [comment]
@silverpill do you have an example `acct` for me??? So that I can implement it in the WordPress plugin and write a proper test for it.

**Comment by silverpill** [comment]
@pfefferle `https://mitra.social/.well-known/webfinger?resource=acct:weekinfediverse@mitra.social`
