### ISSUE TITLE
Describe reverse discovery

### ISSUE THREAD

**Issue by evanp** [swicg/activitypub-webfinger#4]
Explain the process for discovering a Webfinger ID from an ActivityPub ID:

- domain = domain part of the URL
- username = preferredUsername property of the actor
- do Webfinger resolution to confirm that it points to this actor
- optionally take the `subject` property as the canonical Webfinger account

**Comment by pfefferle** [comment]
I also used WebFinger for that. Example:

1. Get WebFinger profile by ActivityPub ID: https://webfinger.net/lookup/?resource=https%3A%2F%2Fnotiz.blog%2Fauthor%2Fmatthias-pfefferle%2F
2. Search for an ID with the `acct:` protocol in the `aliases` array
3. done

But I also like your proposed FEP https://codeberg.org/fediverse/fep/src/branch/main/fep/2c59/fep-2c59.md
