### ISSUE TITLE
Arity

### ISSUE THREAD

**Issue by evanp** [swicg/activitypub-webfinger#5]
What to do if there are more than 1 matching `links` items.

**Comment by pfefferle** [comment]
That is a really good question and I had a lot of issues because of that in the past!

The WebFinger spec says nothing about an order.

**Comment by silverpill** [comment]
@trwnh Lemmy servers can have two actors with the same webfinger address: https://lemmy.ml/.well-known/webfinger?resource=acct:activitypub@lemmy.ml

`properties` is used to differentiate between two `self` links

The exact mechanism could be specified in a FEP, but I think at least the possibility of multiple `self` links in JRD should be mentioned in the report.
