### ISSUE TITLE
Other links properties

### ISSUE THREAD

**Issue by evanp** [swicg/activitypub-webfinger#6]
Avatar and profile page are well-known. Are there others that should/could be useful for AP?

**Comment by pfefferle** [comment]
The required links property for ActivityPub is:

```JSON
{
    "rel": "self",
    "type": "application\/activity+json",
    "href": "https://example.org/author"
}
```

But besides of that there are only Avatar and Profile, see https://webfinger.net/rel/

**Comment by evanp** [comment]
So, ActivityPub actors include a number of additional properties, including:

- `name`
- `preferredUsername`
- `summary`
- `inbox`
- `outbox`
- `followers`
- `following`
- `liked`
- `sharedInbox`
- Other `endpoints`

I don't know if it would every be a helpful optimization to get these from the JRD.
